version: '3.1'

services:
  orders-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders-db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
