version: '3.1'

services:
  customer-db:
    container_name: customer-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer-db
    ports:
      - 5432:5432

  orders-db:
    container_name: orders-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders-db
    ports:
      - 5433:5432

  product-db:
    container_name: product-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-db
    ports:
      - 5434:5432
